name: Update LeetCode Progress GIF

on:
  push:
    paths:
      - 'DashboardScript/generate_progress_gif.py'
      - 'progress.json'
      - 'README.md'

permissions:
  contents: write

jobs:
  generate-gif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system dependencies (ImageMagick + emoji font)
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick fonts-symbola

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install matplotlib celluloid

      - name: Generate progress GIF
        run: python DashboardScript/generate_progress_gif.py

      - name: Commit and push updated GIF
        run: |
          git config --global user.name "LeetCode Bot"
          git config --global user.email "bot@example.com"
          git add leetcode_progress.gif
          git commit -m "🤖 Auto-update LeetCode progress GIF" || echo "No changes to commit"
          git pull --rebase origin main
          git push
