name: Update LeetCode Progress GIF

on:
  push:
    paths:
      - 'DashboardScript/generate_progress_gif.py'
      - 'progress.json'
      - 'README.md'

permissions:
  contents: write  # Required to allow git push

jobs:
  generate-gif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Manim & FFmpeg
        run: |
          sudo apt update
          sudo apt install ffmpeg -y
          pip install manim

      - name: Generate video using Manim
        run: |
          manim -pql DashboardScript/generate_progress_gif.py LeetCodeRace

      - name: Convert to GIF
        run: |
          mkdir -p output
          ffmpeg -y -i media/videos/DashboardScript/generate_progress_gif/480p15/LeetCodeRace.mp4 output/leetcode_progress.gif

      - name: Commit and push updated gif
        run: |
          git config --global user.name "LeetCode Bot"
          git config --global user.email "bot@example.com"
          git add output/leetcode_progress.gif
          git commit -m "🤖 Auto-update LeetCode progress GIF" || echo "No changes to commit"
          git push
