name: Update LeetCode Progress GIF

on:
  push:
    paths:
      - 'DashboardScript/generate_progress_gif.py'
      - 'progress.json'
      - 'README.md'

jobs:
  generate-gif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install matplotlib pillow celluloid

      - name: Run progress animation script
        run: python scripts/generate_progress_gif.py

      - name: Commit and push updated gif
        run: |
          git config --global user.name "LeetCode Bot"
          git config --global user.email "bot@example.com"
          git add leetcode_progress.gif
          git commit -m "🤖 Auto-update LeetCode progress GIF"
          git push
